### ISSUE TITLE
RegenFarms -  modal text in Regenfarm 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/liquidity-mining-dapp#196]
right now on the current havest modal we can still see terms such as GIVfarm and GIVstream - If we are harvesting from a RegenFarm then we should see in place of `GIVfarm` - `RegenFarm` and instead of `GIVstream` we should see `RegenStream`

Also the same for the `?` hover tooltip the text should be replaced according to the above
![image](https://user-images.githubusercontent.com/67759413/158426729-4ae73906-0fde-4649-bb4d-f04926954a70.png)

**Comment by laurenluz** [comment]
@MohammadPCh Can you take this one?

**Comment by laurenluz** [comment]
There are still some text issues:

- [x] - Instead of "GIVfarm" it should be "RegenFarm"
- [x] - Instead of "RegenStream" it would be better to say "[token]stream", so in this case, "FOXstream"
- [x] - "liquid FOX" (missing a space)
- [x] - Tooltip: "Increase your [token, e.g. FOX]stream flowrate when you harvest rewards."

![image](https://user-images.githubusercontent.com/75490971/160178640-de02a790-a797-49c9-aa51-e59ee7fa6a7d.png)

![image](https://user-images.githubusercontent.com/75490971/160178342-4df2c59f-6e38-4775-b16e-89d3dd403754.png)

**Comment by laurenluz** [comment]
This should say "FOXstream"

![image](https://user-images.githubusercontent.com/75490971/160878425-bc9d7d58-8fcf-4446-a228-e4a02311c5f0.png)
